version: "3.7"

services:
  rabbitmq-broker:
    image: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

  register:
    image: "alpt96/mltestingwebframework:register"
    volumes:
      - './services/register:/usr/src/ml-framework'
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - users-db
      - rabbitmq-broker

  login:
    image: "alpt96/mltestingwebframework:login"
    volumes:
      - './services/register:/usr/src/ml-framework'
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - users-db
      - rabbitmq-broker

  views:
    image: "alpt96/mltestingwebframework:api"
    volumes:
      - './services/register:/usr/src/ml-framework'
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  #      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
  #      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq-broker

  users-db:
    build:
      context: ./services/register/project/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  rabbitmq-consumer:
    image: "alpt96/mltestingwebframework:simple-consumer"
    environment:
  #      - RABBITMQ_USERNAME=guest
  #      - RABBITMQ_PASSWORD=guest
      - QUEUE=register-service-queue
      - BROKER=rabbitmq-broker
      - PORT=5672
      - EXCHANGE=requests
    depends_on:
      - rabbitmq-broker

  rabbitmq-producer:
    image: "alpt96/mltestingwebframework:simple-producer"
    environment:
  #      - RABBITMQ_USERNAME=guest
  #      - RABBITMQ_PASSWORD=guest
      - BROKER=rabbitmq-broker
      - EXCHANGE=requests
      - PORT=5672
    depends_on:
      - rabbitmq-broker