version: "3.7"

services:
  rabbitmq-broker:
    image: "rabbitmq:management"
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  register:
    image: "alpt96/mltestingwebframework:register"
    volumes:
      - register-service:/usr/src/ml-framework
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - users-db
      - api

  models:
    image: "alpt96/mltestingwebframework:model_deployment"
    volumes:
      - model-deployment-service:/usr/src/ml-framework
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@models-db:5432/models_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@models-db:5432/models_dev
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - models-db

  model-info:
    image: "alpt96/mltestingwebframework:model_information"
    volumes:
      - model-info-service:/usr/src/ml-framework
    ports:
      - "5004:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@modelstate-db:5432/modelstate_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@modelstate-db:5432/modelstate_dev
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - modelstate-db
      - models-db

  data-provider:
    image: "alpt96/mltestingwebframework:data_provider"
    volumes:
      - data-provider-service:/usr/src/ml-framework
    ports:
      - "5006:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@provider-db:5432/provider_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@provider-db:5432/provider_dev
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - provider-db
      - models-db

  ai-master:
    image: "alpt96/mltestingwebframework:ai_master"
    volumes:
      - ai-master-service:/usr/src/ml-framework
    ports:
      - "5007:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@modelstate-db:5432/modelstate_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@modelstate-db:5432/modelstate_dev
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - modelstate-db
      - rabbitmq-broker

  ai-slave:
    image: "alpt96/mltestingwebframework:ai_slave"
    volumes:
      - ai-slave-service:/usr/src/ml-framework
      - "/etc:/usr/etc"
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - LC_ALL=en_US.utf-8
      - LANG=en_US.utf-8
    deploy:
      placement:
        constraints: [node.hostname == alp-acer-netbook]
    depends_on:
      - ai-master
      - rabbitmq-broker

  ai-slave-arm:
    image: "alpt96/mltestingwebframework:ai_slave_arm"
    volumes:
      - ai-slave-service:/usr/src/ml-framework
      - "/etc:/usr/etc"
    ports:
      - "5009:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - LC_ALL=en_US.utf-8
      - LANG=en_US.utf-8
    deploy:
      placement:
        constraints: [node.hostname == raspberrypi]
    depends_on:
      - ai-master
      - rabbitmq-broker

  login:
    image: "alpt96/mltestingwebframework:login"
    volumes:
      - login-service:/usr/src/ml-framework
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - users-db
      - api

  mailer:
    image: "alpt96/mltestingwebframework:mailer"
    volumes:
      - mailer-service:/usr/src/ml-framework
    ports:
      - "5008:5001"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - users-db
      - models_db

  views:
    image: "alpt96/mltestingwebframework:views"
    volumes:
      - views-service:/usr/src/ml-framework
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - api

  api:
    image: "alpt96/mltestingwebframework:api"
    volumes:
      - api-service:/usr/src/ml-framework
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    deploy:
      placement:
        constraints: [node.role == manager]

  users-db:
    image: "alpt96/mltestingwebframework:users_db"
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  models-db:
    image: "alpt96/mltestingwebframework:models_db"
    ports:
      - "5433:5432"
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  modelstate-db:
    image: "alpt96/mltestingwebframework:modelstate_db"
    ports:
      - "5434:5432"
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  provider-db:
    image: "alpt96/mltestingwebframework:provider_db"
    ports:
      - "5435:5432"
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  register-service:
  model-deployment-service:
  model-info-service:
  data-provider-service:
  ai-master-service:
  ai-slave-service:
  login-service:
  views-service:
  api-service:
  mailer-service:
